name: 'Sarah: Run calculator build and test?'

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Clone repo
      uses: actions/checkout@v3
    - name: make
      run: |-
        cd calculator
        make
    - name: run calculator
      run: |-
        cd calculator
        ./calculator 2 + 1
